<a href="https://colab.research.google.com/github/Sjleerodls/Data_Analysis/blob/main/lab_da/da_self_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# np.newaxis, np.expand_dims

* 1차원 배열을 2차원 배열로 변환하는 방법(배열에 새로운 축을 추가하는 방법)
* np.newaxis를 한 번 사용할 때마다 한 차원씩 차원이 증가함.
    * 1차원 배열 -> 2차원 배열
    * 2차원 배열 -> 3차원 배열

## np.newaxis 사용

In [6]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
a

(6,)


array([1, 2, 3, 4, 5, 6])

In [5]:
a2 = a[np.newaxis, :]
print(a2.shape)
a2

(1, 6)


array([[1, 2, 3, 4, 5, 6]])

In [12]:
# 첫 번째 차원에 축을 삽입해 1차원 배열을 행 벡터로 변환
row_vector = a[np.newaxis, :]
print(row_vector.shape)
row_vector

(1, 6)


array([[1, 2, 3, 4, 5, 6]])

In [11]:
# 열 벡터의 경우 두 번째 차원을 따라 축을 삽입
col_vector = a[:, np.newaxis]
print(col_vector.shape)
col_vector

(6, 1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## np.expand_dims 사용

In [13]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [14]:
# 인덱스 위치 1에 축을 추가
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [15]:
# 인덱스 위치 0에 축을 추가
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

## np.vstack()

In [17]:
# 두 개의 기존 배열을 수직으로 쌓기
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
              [4, 4]])

np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

## np.hstack()

In [18]:
# 수평으로 쌓기
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## hsplit()

* 배열을 여러개의 작은 배열로 나눌 수 있음.
* hsplit()을 사용할 때 배열의 크기가 일치해야 사용이 가능함.

In [20]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [24]:
np.hsplit(x, 6)

[array([[ 1,  2],
        [13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8],
        [19, 20]]),
 array([[ 9, 10],
        [21, 22]]),
 array([[11, 12],
        [23, 24]])]

In [25]:
np.hsplit(x, (3,4)) # 세 번째와 네 번쨰 열 다음에 배열을 분할

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]