<a href="https://colab.research.google.com/github/Sjleerodls/Data_Analysis/blob/main/lab_da/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 고급기능

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# np.ndarray 속성

In [2]:
arr = np.ones(shape=(2,3))

In [3]:
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
arr.shape   # shape 속성 : 배열의 각 축(axis)을 따라서 있는 원소의 개수들의 tuple.

(2, 3)

In [13]:
arr.dtype   # dtype 속성 : 배열 원소의 데이터 타입.

dtype('float64')

In [14]:
arr.size    # size 속성 : 배열의 모든 원소 개수.

6

In [16]:
arr.ndim    # ndim 속성 : 배열의 차원(dimension). 배열의 축(axis)의 개수.

2

In [19]:
arr = np.arange(10)     # 0 이상 10 미만의 (10개의) 정수들로 이루어진 배열.

In [21]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
print('dtype:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtype: int64
ndim: 1
shape: (10,)
size: 10


In [24]:
arr = np.arange(1, 25).reshape((2, 3, 4))

In [25]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [26]:
print('dtype:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtype: int64
ndim: 3
shape: (2, 3, 4)
size: 24


# Indexing

인덱스를 사용해서 배열 원소를 참조.

In [28]:
print(arr)  #> 3d array(3차원 배열)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [33]:
print(arr[0])   #> 2d array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
print(arr[0, 0])    #> 1d array

[1 2 3 4]


In [37]:
print(arr[0][0])    #> 1d array

[1 2 3 4]


In [39]:
print(arr[0, 0, 0]) #> int -> 스칼라()

1


In [40]:
print(arr[0][0][0])

1


* Python list 인덱스 사용 방법 :
    * `list[i][j][k]...`
* NumPy ndarray 인덱스 사용 방법 :
    * `array[i, j, k, ...]`
    * `array[i][j][k]...`

# Slicing

## 1차원 배열의 slicing

In [41]:
np.random.seed(1)
arr = np.random.randint(100, size=10)   # [0, 100) 범위의 정수 난수 10개로 이루어진 1d array.

In [42]:
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [44]:
print(arr[1:5])

[12 72  9 75]


In [46]:
print(arr[:3])  #> 시작 인덱스 0은 생략 가능

[37 12 72]


In [50]:
print(arr[-3:])     #> 배열의 끝까지 자를 때는 마지막 인덱스는 생략 가능.
                    # 배열의 끝에서부터 거꾸로 매기는 인덱스는 음수 인덱스.

[64 16  1]


In [57]:
print(arr[0:1])     #> slicing의 결과 -> 배열
print(arr[0])       #> indexing의 결과 -> 원소(스칼라)

[37]
37


In [58]:
print(type(arr[0:1]))
print(type(arr[0]))

<class 'numpy.ndarray'>
<class 'numpy.int64'>


## 2차원 배열의 slicing

In [59]:
arr = np.arange(1, 21).reshape((4,5))

In [60]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [76]:
# 2차원 배열 arr의 첫 2개의 1차원 배열
# print(arr[:2])
print(arr[:2, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [63]:
# 2차원 배열 arr의 마지막 2개의 1차원 배열
print(arr[-2:])

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [67]:
print(arr[0,0:3])
print(arr[1,0:3])

[1 2 3]
[6 7 8]


In [68]:
print(arr[:2, :3])

[[1 2 3]
 [6 7 8]]


In [78]:
print(arr[1:3, 1:4])

[[ 7  8  9]
 [12 13 14]]


In [81]:
print(arr[1:3])
print(arr[1:3][1:4])    # 위쪽 셀의 결과와 비교!

[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[11 12 13 14 15]]


## 3차원 배열의 slicing

In [82]:
arr = np.arange(1, 61).reshape((3, 4, 5))

In [83]:
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [84]:
print(arr[:2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [85]:
print(arr[:2, :, :])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [89]:
# print(arr[:2, :2, :])
print(arr[:2, :2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


In [90]:
print(arr[:2, :2, :2])

[[[ 1  2]
  [ 6  7]]

 [[21 22]
  [26 27]]]


In [93]:
print(arr[:1, :, :])    #> 결과 : 3d array  / slicing

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


In [94]:
print(arr[0, :, :])     #> 결과 : 2d array  / indexing

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# Shape(모양) 변경
    * `np.ndarray.reshape(arg)`
    * `np.ndarray.ravel()`
    * `np.ndarray.flatten()`
    * `np.newaxis` 속성

## reshape

In [122]:
arr_1d = np.arange(12)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [124]:
# arr_1d를 (4, 3) shape의 2d array 로 변환
arr_2d = arr_1d.reshape((4, -1))    # (4, 3) 파이썬 내부에서 자동으로 계산이 이루어짐.
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [125]:
# reshape 메서드의 아규먼트를 전달할 때 자동으로 계산할 수 있는 차원의 값은 -1을 사용할 수 있음.
arr_2d = arr_1d.reshape((-1, 4))    #> (3, 4)
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [127]:
# 2차원 배열 arr_2d를 1차원 배열로 변환.
result = arr_2d.reshape((3 * 4))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [128]:
result = arr_2d.reshape((-1,))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [130]:
result = arr_2d.reshape((-1))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [131]:
arr_1d = np.arange(60)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [132]:
# 1차원 배열 arr_1d의 모양을 (3, 4, 5)로 변환
result = arr_1d.reshape((3, 4, -1)) # (3, 4, 5)
print(result)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [133]:
# 1차원 배열 arr_1d의 모양을 (5, 4, 3)로 변환
result = arr_1d.reshape((5, 4, -1)) # (5, 4, 3)
print(result)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]

 [[48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]


## ravel vs flatten

* flatten
    * n차원 배열 ndarray를 1차원 배열로 변환한 "복사본"을 리턴.
    * 원본 배열과는 별개의 새로운 배열을 메모리에 만들어서 리턴.
* ravel
    * n차원 배열 ndarray를 1차원 배열로 변환한 "뷰(view)"를 리턴.
    * 별개의 새로운 배열을 만드는 것이 아니라, 원본 배열의 모양을 1차원으로 보여줄 뿐.

In [109]:
arr_2d = np.arange(12).reshape((3, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [110]:
flattened = arr_2d.flatten()    # n차원 배열을 무조건 1차원 배열로 만들어버림.
print(flattened)        # 복사본으로 원본에는 영향을 미치지 않음.

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [112]:
flattened[0] = 123  #> 1차원 배열 flattened에 첫번째 위치에 새로운 값을 재할당.
print(flattened)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [114]:
print(arr_2d)   # 원본 2차원 배열과는 무관.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [119]:
raveled = arr_2d.ravel()
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [121]:
raveled[0] = 123    # 원본에도 영향을 미침.
print(arr_2d)       # 원본 2차원 배열의 값을 변경!
print(raveled)      # 1차원 배열의 원소를 변경

[[123   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[123   1   2   3   4   5   6   7   8   9  10  11]


## `np.newaxis` 속성을 사용한 차원 늘리기

In [134]:
arr = np.arange(1, 6)
print(arr)

[1 2 3 4 5]


In [136]:
arr.shape   #> (5,)

(5,)

In [138]:
result = arr[np.newaxis, :]
print(result)

[[1 2 3 4 5]]


In [140]:
result.shape    #> (1, 5)

(1, 5)

In [142]:
print(arr)  # 원본은 유지중

[1 2 3 4 5]


In [143]:
result = arr[:, np.newaxis]
print(result)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [144]:
result.shape    # (5, 1)

(5, 1)

In [146]:
print(arr_2d)   #> shape : (3, 4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [150]:
result = arr_2d[np.newaxis, :, :]
print(result)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


In [149]:
result.shape    #> (1, 3, 4)

(1, 3, 4)

In [151]:
result = arr_2d[:, :, np.newaxis]
print(result)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]


In [152]:
result.shape    #> (3, 4, 1)

(3, 4, 1)

In [153]:
result = arr_2d[:, np.newaxis, :]
print(result)

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]


In [154]:
result.shape

(3, 1, 4)

In [155]:
result = arr[:, np.newaxis, np.newaxis]
print(result)

[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]]


In [156]:
result.shape

(5, 1, 1)

# concatenate

* `np.concatenate([array1, array2, ...], axis=0)` : 특정 축(axis) 방향으로 배열 이어붙이기.
* `np.r_[array1, array2]` : 행들을 이어 붙이기. axis=0 방향으로 이어붙이기.
* `np.c_[array1, array2]` : 컬럼들을 이어붙이기. axis=1 방향으로 이어붙이기.

In [160]:
# (2, 3) shape의 2d array
arr1 = np.arange(1, 7).reshape((2, 3))
print(arr1)

[[1 2 3]
 [4 5 6]]


In [165]:
# (1, 3) shape의 2d array
arr2 = np.array([[7, 8, 9]])
print(arr2)

[[7 8 9]]


In [166]:
# (2, 1) shape의 2d array
arr3 = np.array([[10], [11]])
print(arr3)

[[10]
 [11]]


In [167]:
result = np.concatenate([arr1, arr2])   # axis=0 생략 가능(default arg)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [170]:
np.r_[arr1, arr2]   # arr1과 arr2가 2d array일 때 concatenate를 간단히.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [171]:
result = np.concatenate([arr1, arr3], axis=1)
print(result)

[[ 1  2  3 10]
 [ 4  5  6 11]]


In [172]:
np.c_[arr1, arr3]   # arr1과 arr3이 2d array 일 때 concatenate를 간단히.

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11]])

# Broadcasting

* np.ndarray의 연산(+, -, *, /, //, %, >, <, ==, ...)은 같은 위치(인덱스)의 원소들끼리(elementwise) 연산이 수행됨.
* 서로 모양(shape)이 다른 배열들끼리 연산이 가능한 경우가 있음. broadcast가 가능한 경우.

In [173]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [174]:
print(a + b)

[5 7 9]


In [177]:
c = np.array([7, 8])
# print(a + c)
#> ValueError : (3,) shape의  1d array와 (2,) shape의 1d array는 서로 연산이 불가능함.

## ndarray와 scalar의 연산

항상 broadcast가 가능. 항상 연산이 가능. 스칼라를 배열의 각 원소마다 연산을 수행.

In [178]:
print(a + 10)

[11 12 13]


## 2d array와 1d array 또는 2d array에서의 broadcast

In [179]:
a = np.arange(1, 7).reshape((2, 3)) # shape : (2, 3)
print(a)

[[1 2 3]
 [4 5 6]]


In [180]:
b = np.array([7, 8, 9]) # shape: (3,)
print(b)

[7 8 9]


In [182]:
# (3, ) shape의 1d array -> (1, 3) shape 2d array -> (2, 3) shape으로 broadcast
print(a + b)

[[ 8 10 12]
 [11 13 15]]


In [184]:
b = np.array([[5], [10]]) # shpae : (2, 1)
b

array([[ 5],
       [10]])

In [186]:
# (2, 1) shape의 2d array -> (2, 3) shape으로 broadcast
print(a + b)

[[ 6  7  8]
 [14 15 16]]


broadcasting이 가능한 경우:

* 브로드캐스팅은 누락되거나 길이가 1인 차원에 대해서만 수행.
* 이어지는 차원의 축의 길이가 같은 경우 브로드캐스팅이 가능함.

In [187]:
a = np.arange(12).reshape((4, 3))
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [188]:
b = np.array([[1, 1, 1,], [2, 2, 2]])
print(b)

[[1 1 1]
 [2 2 2]]


In [190]:
print(a + b)

ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 

In [193]:
b = np.array([2, 2, 2])
print(b)

[2 2 2]


In [194]:
print(a + b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


## broadcast 활용

* 표준화(standardization): 값들의 평균이 0이 되고, 표준편차가 1이 되도록 값을 스케일링하는 것.
* 정규화(normalization): 최솟값이 0이 되고 최댓값이 1이 되도록 값들을 변환.

## 표준화

In [195]:
x = np.array([1, 2, 3, 4, 5])

In [205]:
mu = x.mean()    # 평균, np.mean(x)
print(mu)

3.0


In [206]:
sigma = x.std()     # 표준편차, np.std(x)
print(sigma)

1.4142135623730951


In [207]:
x_scaled = (x - mu) / sigma     # 표준화 공식
print(x_scaled)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [208]:
np.mean(x_scaled)

np.float64(0.0)

In [209]:
np.std(x_scaled)

np.float64(0.9999999999999999)

## 정규화

In [212]:
x_min = np.min(x)   # 배열 x의 최솟값
x_max = np.max(x)   # 배열 x의 최댓값
print(x_min, x_max)

1 5


In [213]:
x_scaled = (x - x_min) / (x_max - x_min)    # 정규화 공식
print(x_scaled)

[0.   0.25 0.5  0.75 1.  ]


### 2차원 배열에서 표준화, 정규화

In [214]:
# (3, 2) shape 2d array
X = np.arange(1, 7).reshape((3, 2))
print(X)

[[1 2]
 [3 4]
 [5 6]]


In [220]:
# 표준화
me = np.mean(X)
st = np.std(X)

x_scaled = (X - me) / st
print(x_scaled)

[[-1.46385011 -0.87831007]
 [-0.29277002  0.29277002]
 [ 0.87831007  1.46385011]]


In [222]:
print(np.mean(x_scaled))    # 평균
print(np.std(x_scaled))     # 표준편차

-3.700743415417188e-17
1.0


In [217]:
# 정규화
x_min = np.min(X)
x_max = np.max(X)

x_scaled = (X - x_min) / (x_max - x_min)
print(x_scaled)

[[0.  0.2]
 [0.4 0.6]
 [0.8 1. ]]


In [225]:
np.mean(X, axis=0, keepdims=True)

array([[3., 4.]])

In [226]:
np.mean(X, axis=1, keepdims=True)

array([[1.5],
       [3.5],
       [5.5]])

axis=0 축 방향으로 표준화

In [227]:
X_scaled = (X - np.mean(X, axis=0, keepdims=True)) / np.std(X, axis=0, keepdims=True)
print(X_scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


axis=1 축 방향으로 표준화

In [228]:
X_scaled = (X - np.mean(X, axis=1, keepdims=True)) / np.std(X, axis=1, keepdims=True)
print(X_scaled)

[[-1.  1.]
 [-1.  1.]
 [-1.  1.]]


axis=0 축 방향으로 정규화

In [230]:
X_min = np.min(X, axis=1, keepdims=True)
X_max = np.max(X, axis=1, keepdims=True)
X_scaled = (X - X_min) / (X_max - X_min)
print(X_scaled)

[[0. 1.]
 [0. 1.]
 [0. 1.]]


### seaborn 모듈에서 iris 데이터셋을 로드, 표준화

In [243]:
iris = sns.load_dataset('iris')

In [244]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [245]:
iris = iris.drop('species', axis=1)
iris.tail()

sepal_length  sepal_width  petal_length  petal_width
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

In [246]:
# 표준화
iris_scaled = (iris - np.mean(iris)) / np.std(iris)
print(iris_scaled)

     sepal_length  sepal_width  petal_length  petal_width
0        1.981701     0.081720     -1.173409    -4.297133
1        1.739365    -1.069264     -1.173409    -4.297133
2        1.497029    -0.608870     -1.230246    -4.297133
3        1.375861    -0.839067     -1.116571    -4.297133
4        1.860533     0.311917     -1.173409    -4.297133
..            ...          ...           ...          ...
145      3.920386    -1.069264      0.986414    -1.532857
146      3.435715    -2.220248      0.872739    -2.059386
147      3.678051    -1.069264      0.986414    -1.927753
148      3.314547    -0.148477      1.100088    -1.532857
149      2.951043    -1.069264      0.929576    -2.191018

[150 rows x 4 columns]


In [248]:
print(np.mean(iris_scaled))
print(np.std(iris_scaled))

-0.21744333042594216
sepal_length    1.0
sepal_width     1.0
petal_length    1.0
petal_width     1.0
dtype: float64
