<a href="https://colab.research.google.com/github/Sjleerodls/Data_Analysis/blob/main/lab_da/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 고급기능

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# np.ndarray 속성

In [2]:
arr = np.ones(shape=(2,3))

In [3]:
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
arr.shape   # shape 속성 : 배열의 각 축(axis)을 따라서 있는 원소의 개수들의 tuple.

(2, 3)

In [13]:
arr.dtype   # dtype 속성 : 배열 원소의 데이터 타입.

dtype('float64')

In [14]:
arr.size    # size 속성 : 배열의 모든 원소 개수.

6

In [16]:
arr.ndim    # ndim 속성 : 배열의 차원(dimension). 배열의 축(axis)의 개수.

2

In [19]:
arr = np.arange(10)     # 0 이상 10 미만의 (10개의) 정수들로 이루어진 배열.

In [21]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
print('dtype:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtype: int64
ndim: 1
shape: (10,)
size: 10


In [24]:
arr = np.arange(1, 25).reshape((2, 3, 4))

In [25]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [26]:
print('dtype:', arr.dtype)
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)

dtype: int64
ndim: 3
shape: (2, 3, 4)
size: 24


# Indexing

인덱스를 사용해서 배열 원소를 참조.

In [28]:
print(arr)  #> 3d array(3차원 배열)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [33]:
print(arr[0])   #> 2d array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
print(arr[0, 0])    #> 1d array

[1 2 3 4]


In [37]:
print(arr[0][0])    #> 1d array

[1 2 3 4]


In [39]:
print(arr[0, 0, 0]) #> int -> 스칼라()

1


In [40]:
print(arr[0][0][0])

1


* Python list 인덱스 사용 방법 :
    * `list[i][j][k]...`
* NumPy ndarray 인덱스 사용 방법 :
    * `array[i, j, k, ...]`
    * `array[i][j][k]...`

# Slicing

## 1차원 배열의 slicing

In [41]:
np.random.seed(1)
arr = np.random.randint(100, size=10)   # [0, 100) 범위의 정수 난수 10개로 이루어진 1d array.

In [42]:
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [44]:
print(arr[1:5])

[12 72  9 75]


In [46]:
print(arr[:3])  #> 시작 인덱스 0은 생략 가능

[37 12 72]


In [50]:
print(arr[-3:])     #> 배열의 끝까지 자를 때는 마지막 인덱스는 생략 가능.
                    # 배열의 끝에서부터 거꾸로 매기는 인덱스는 음수 인덱스.

[64 16  1]


In [57]:
print(arr[0:1])     #> slicing의 결과 -> 배열
print(arr[0])       #> indexing의 결과 -> 원소(스칼라)

[37]
37


In [58]:
print(type(arr[0:1]))
print(type(arr[0]))

<class 'numpy.ndarray'>
<class 'numpy.int64'>


## 2차원 배열의 slicing

In [59]:
arr = np.arange(1, 21).reshape((4,5))

In [60]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [76]:
# 2차원 배열 arr의 첫 2개의 1차원 배열
# print(arr[:2])
print(arr[:2, :])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [63]:
# 2차원 배열 arr의 마지막 2개의 1차원 배열
print(arr[-2:])

[[11 12 13 14 15]
 [16 17 18 19 20]]


In [67]:
print(arr[0,0:3])
print(arr[1,0:3])

[1 2 3]
[6 7 8]


In [68]:
print(arr[:2, :3])

[[1 2 3]
 [6 7 8]]


In [78]:
print(arr[1:3, 1:4])

[[ 7  8  9]
 [12 13 14]]


In [81]:
print(arr[1:3])
print(arr[1:3][1:4])    # 위쪽 셀의 결과와 비교!

[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[11 12 13 14 15]]


## 3차원 배열의 slicing

In [82]:
arr = np.arange(1, 61).reshape((3, 4, 5))

In [83]:
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [84]:
print(arr[:2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [85]:
print(arr[:2, :, :])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [89]:
# print(arr[:2, :2, :])
print(arr[:2, :2])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


In [90]:
print(arr[:2, :2, :2])

[[[ 1  2]
  [ 6  7]]

 [[21 22]
  [26 27]]]


In [93]:
print(arr[:1, :, :])    #> 결과 : 3d array  / slicing

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


In [94]:
print(arr[0, :, :])     #> 결과 : 2d array  / indexing

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# Shape(모양) 변경
    * `np.ndarray.reshape(arg)`
    * `np.ndarray.ravel()`
    * `np.ndarray.flatten()`
    * `np.newaxis` 속성

## reshape

In [122]:
arr_1d = np.arange(12)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [124]:
# arr_1d를 (4, 3) shape의 2d array 로 변환
arr_2d = arr_1d.reshape((4, -1))    # (4, 3) 파이썬 내부에서 자동으로 계산이 이루어짐.
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [125]:
# reshape 메서드의 아규먼트를 전달할 때 자동으로 계산할 수 있는 차원의 값은 -1을 사용할 수 있음.
arr_2d = arr_1d.reshape((-1, 4))    #> (3, 4)
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [127]:
# 2차원 배열 arr_2d를 1차원 배열로 변환.
result = arr_2d.reshape((3 * 4))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [128]:
result = arr_2d.reshape((-1,))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [130]:
result = arr_2d.reshape((-1))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [131]:
arr_1d = np.arange(60)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [132]:
# 1차원 배열 arr_1d의 모양을 (3, 4, 5)로 변환
result = arr_1d.reshape((3, 4, -1)) # (3, 4, 5)
print(result)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [133]:
# 1차원 배열 arr_1d의 모양을 (5, 4, 3)로 변환
result = arr_1d.reshape((5, 4, -1)) # (5, 4, 3)
print(result)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]

 [[48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]]


## ravel vs flatten

* flatten
    * n차원 배열 ndarray를 1차원 배열로 변환한 "복사본"을 리턴.
    * 원본 배열과는 별개의 새로운 배열을 메모리에 만들어서 리턴.
* ravel
    * n차원 배열 ndarray를 1차원 배열로 변환한 "뷰(view)"를 리턴.
    * 별개의 새로운 배열을 만드는 것이 아니라, 원본 배열의 모양을 1차원으로 보여줄 뿐.

In [109]:
arr_2d = np.arange(12).reshape((3, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [110]:
flattened = arr_2d.flatten()    # n차원 배열을 무조건 1차원 배열로 만들어버림.
print(flattened)        # 복사본으로 원본에는 영향을 미치지 않음.

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [112]:
flattened[0] = 123  #> 1차원 배열 flattened에 첫번째 위치에 새로운 값을 재할당.
print(flattened)

[123   1   2   3   4   5   6   7   8   9  10  11]


In [114]:
print(arr_2d)   # 원본 2차원 배열과는 무관.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [119]:
raveled = arr_2d.ravel()
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [121]:
raveled[0] = 123    # 원본에도 영향을 미침.
print(arr_2d)       # 원본 2차원 배열의 값을 변경!
print(raveled)      # 1차원 배열의 원소를 변경

[[123   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[123   1   2   3   4   5   6   7   8   9  10  11]
