<a href="https://colab.research.google.com/github/Sjleerodls/Data_Analysis/blob/main/lab_da/ml16_ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network (인공 신경망)

# Imports

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_validate, train_test_split
from sklearn.metrics import accuracy_score

import tensorflow as tf
import keras

# Iris 데이터 셋

In [ ]:
data, target = datasets.load_iris(return_X_y=True)

## 이진 분류

* 0(setosa)과 0이 아닌(versicolor, virginica) 클래스 분류
* 2개의 특성만 사용.

In [ ]:
X = data[:, :2]     # data에서 행은 모두 선택, 열은 첫 2개만 선택.
X.shape

(150, 2)

In [ ]:
y = (target == 0).astype('int')
y   # 0 -> 0, 1 & 2 -> 1 변환.

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## SGD Classifier (확률적 경사 하강법)

In [ ]:
# Logistic  손실 함수를 최소화하는 확률적 경사 하강법 분류 모델을 생성.
# 최대 epoch(반복 횟수)를 10회로 설정.
sgd = SGDClassifier(loss='log_loss', max_iter = 10, n_jobs=-1, random_state=42)

In [ ]:
sgd.fit(X, y)       # SGD 모델 훈련 - 손실함수를 최소로 만들어 주는 절편(intercept)과 계수들(coefficient)을 찾는 과정

SGDClassifier(loss='log_loss', max_iter=10, n_jobs=-1, random_state=42)

In [ ]:
sgd.intercept_

array([53.74585533])

In [ ]:
sgd.coef_

array([[-105.81024473,  161.57516803]])

In [ ]:
# 훈련 셋 예측 확률
y_prob = sgd.predict_proba(X)       # 예측 확률

In [ ]:
y_prob[:5]

array([[0.00000000e+00, 1.00000000e+00],
       [2.05876360e-09, 9.99999998e-01],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00]])

In [ ]:
y_pred = sgd.predict(X)     # 예측 값
y_pred[:5]

array([1, 1, 1, 1, 1])

In [ ]:
accuracy_score(y, y_pred)

0.9933333333333333

## 신경망(Neural Network)

In [ ]:
inputs = keras.layers.Input(shape=(2,))     # 입력층(input layer)

In [ ]:
dense = keras.layers.Dense(units=1, activation='sigmoid')   # 출력층(output layer)

In [ ]:
model = keras.Sequential(layers=[inputs, dense])    # 신경망 모델 생성

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# 신경망 모델 컴파일 : optimizer(최적화 알고리즘), loss(손실함수), metrics
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.binary_crossentropy,
              metrics=[keras.metrics.binary_accuracy])

In [ ]:
# 신경망 모델 훈련
model.fit(x=X, y=y, batch_size=1, epochs=10)

Epoch 1/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - binary_accuracy: 0.6751 - loss: 0.6080
Epoch 2/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.6857 - loss: 0.5413
Epoch 3/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - binary_accuracy: 0.7639 - loss: 0.4235
Epoch 4/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - binary_accuracy: 0.8724 - loss: 0.4206
Epoch 5/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - binary_accuracy: 0.8073 - loss: 0.3811
Epoch 6/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.9516 - loss: 0.3147
Epoch 7/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.9524 - loss: 0.3098
Epoch 8/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.9775 - loss: 0.2919
Epoch 9/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9718 - loss: 0.2730
Epoch 10/10
150/150 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.9537 - loss: 0.2954


In [ ]:
# 신경망 모델 훈련을 통해서 찾은 파라미터들
model.weights

[<Variable path=sequential/dense/kernel, shape=(2, 1), dtype=float32, value=[[-1.2197206]
  [ 1.9609605]]>,
 <Variable path=sequential/dense/bias, shape=(1,), dtype=float32, value=[0.24467322]>]

In [ ]:
# 신경망 모델 평가
model.evaluate(x=X, y=y)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - binary_accuracy: 0.9921 - loss: 0.2971


[0.25111693143844604, 0.9933333396911621]

In [ ]:
# 예측값 - 활성화 함수의 리턴값. 시그모이드 함수의 리턴값. 클래스(레이블)이 1이 될 확률.
y_pred = model.predict(X)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step


In [ ]:
y_pred.shape

(150, 1)

In [ ]:
# 예측 레이블
y_pred_label = (y_pred > 0.5).astype('int').ravel()
y_pred_label

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 은닉층(hidden layer)을 가지고 있는 신경망

In [ ]:
inputs = keras.layers.Input(shape=(2,))     # 입력층
dense1 = keras.layers.Dense(units=2, activation='sigmoid')  # 은닉층
dense2 = keras.layers.Dense(units=1, activation='sigmoid')  # 출력층

In [ ]:
model = keras.Sequential(layers=[inputs, dense1, dense2])   # 신경망 생성

In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# 모델 컴파일 :
# 어떤 손실함수(loss)를 어떤 평가 기준(metrics)으로 어떻게 최적화(optimizer)할 것인 지를 설정
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.binary_crossentropy,
              metrics=[keras.metrics.binary_accuracy])

In [ ]:
# 모델 훈련
model.fit(X, y, batch_size=1, epochs=1_000, verbose=0)      # verbose : 출력 없이 실행

In [ ]:
model.weights

[<Variable path=sequential_1/dense_1/kernel, shape=(2, 2), dtype=float32, value=[[ 3.9020164  1.1055126]
  [-5.2314906  0.7393519]]>,
 <Variable path=sequential_1/dense_1/bias, shape=(2,), dtype=float32, value=[-4.8161225  0.0570796]>,
 <Variable path=sequential_1/dense_2/kernel, shape=(2, 1), dtype=float32, value=[[-11.643484]
  [  3.106098]]>,
 <Variable path=sequential_1/dense_2/bias, shape=(1,), dtype=float32, value=[2.784073]>]

In [ ]:
y_pred = model.predict(x=X)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


In [ ]:
y_pred_label = (y_pred > 0.5).astype('int').ravel()     # ravel() : 1차원 배열로 변환
y_pred_label

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.mean(y == y_pred_label)

np.float64(0.9933333333333333)

## 4개 특성을 모두 사용한 다중 클래스 분류 - SGD

In [36]:
data.shape  # (150 samples, 4 features)

(150, 4)

In [37]:
data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [38]:
np.unique(target, return_counts=True)

(array([0, 1, 2]), array([50, 50, 50]))

In [42]:
sgd = SGDClassifier(loss='log_loss', random_state=42)

In [43]:
sgd.fit(X=data, y=target)

SGDClassifier(loss='log_loss', random_state=42)

In [44]:
sgd.intercept_

array([   4.97012943,  128.91629652, -130.52603923])

In [45]:
sgd.coef_

array([[   7.32064421,   13.17715959,  -27.57442655,  -12.68911664],
       [  36.72801312,  -95.62396704,   33.04272408,  -96.76701144],
       [-123.44647495, -105.30456435,  149.42075067,  157.58173689]])

In [47]:
pred = sgd.predict(X=data)
pred

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [48]:
accuracy_score(target, pred)

0.62

## 4개 특성을 모두 사용한 다중 클래스 분류 - 신경망

In [55]:
model = keras.Sequential("")      # Sequential(완전 연결 신경망) 생성

In [56]:
model.add(keras.layers.Input(shape=(4,)))   # 신경망에 입력층 추가
model.add(keras.layers.Dense(units=3, activation='softmax'))    # 신경망에 출력층 추가
# 다중 클래스 분류에서 활성화 함수는 softmax!

In [57]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15 (60.00 B)

 Trainable params: 15 (60.00 B)

 Non-trainable params: 0 (0.00 B)

In [59]:
# 모델 컴파일
model.compile(optimizer=keras.optimizers.SGD(),
              loss=keras.losses.sparse_categorical_crossentropy,
              metrics=[keras.metrics.sparse_categorical_accuracy])

In [61]:
# 모델 훈련
model.fit(x=data, y=target, epochs=1_000, verbose=0)

In [62]:
# 모델 훈련 후 신경망이 찾은 모델 파라미터(가중치, weights)
model.weights

[<Variable path=sequential_4/dense_3/kernel, shape=(4, 3), dtype=float32, value=[[ 0.29941297  0.4459917  -1.1392199 ]
  [ 1.6917466  -0.62529814 -2.0033064 ]
  [-1.8907646   0.3454752   2.512859  ]
  [-0.45437613 -0.62383044  2.16692   ]]>,
 <Variable path=sequential_4/dense_3/bias, shape=(3,), dtype=float32, value=[ 0.2859882   0.49590895 -0.78189945]>]

In [63]:
predicts = model.predict(x=data)

1/5 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step


In [65]:
predicts.shape

(150, 3)

In [66]:
predicts[:5]

array([[9.8296517e-01, 1.7034383e-02, 4.2744028e-07],
       [9.4911999e-01, 5.0876550e-02, 3.4913023e-06],
       [9.7447950e-01, 2.5518961e-02, 1.4696108e-06],
       [9.5157343e-01, 4.8420817e-02, 5.7852030e-06],
       [9.8663515e-01, 1.3364458e-02, 3.4237306e-07]], dtype=float32)

In [67]:
predicts[-5:]

array([[6.6797767e-04, 1.6014270e-01, 8.3918923e-01],
       [3.9183075e-04, 1.9307239e-01, 8.0653572e-01],
       [9.9110953e-04, 2.4278001e-01, 7.5622886e-01],
       [6.4173329e-04, 8.8510774e-02, 9.1084743e-01],
       [1.1415883e-03, 2.1183893e-01, 7.8701949e-01]], dtype=float32)

In [68]:
model.evaluate(x=data, y=target)

5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 111ms/step - loss: 0.1263 - sparse_categorical_accuracy: 0.9842


[0.16919833421707153, 0.9800000190734863]